"""add_chat_appointments_saved_listings_saved_searches

Revision ID: 932bc3c48f1a
Revises: a3e7f1c2d4b9
Create Date: 2026-04-16 17:27:49.039523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '932bc3c48f1a'
down_revision: Union[str, None] = 'a3e7f1c2d4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_notified_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('saved_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_listings_listing_id'), 'saved_listings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_saved_listings_user_id'), 'saved_listings', ['user_id'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('user_a_id', sa.UUID(), nullable=False),
    sa.Column('user_b_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['match_interests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('proposer_id', sa.UUID(), nullable=False),
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type', sa.String(length=20), nullable=False),
    sa.Column('proposed_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alt_time_1', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alt_time_2', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_room_id'), 'appointments', ['room_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.drop_constraint('uq_post_upvote_user', 'community_post_upvotes', type_='unique')
    op.drop_index('ix_community_replies_post_id', table_name='community_replies')
    op.create_foreign_key(None, 'households', 'listings', ['listing_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'households', 'users', ['admin_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'users', 'households', ['household_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.alter_column('verifications', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verifications', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'households', type_='foreignkey')
    op.drop_constraint(None, 'households', type_='foreignkey')
    op.create_index('ix_community_replies_post_id', 'community_replies', ['post_id'], unique=False)
    op.create_unique_constraint('uq_post_upvote_user', 'community_post_upvotes', ['post_id', 'user_id'])
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_appointments_room_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_saved_listings_user_id'), table_name='saved_listings')
    op.drop_index(op.f('ix_saved_listings_listing_id'), table_name='saved_listings')
    op.drop_table('saved_listings')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    # ### end Alembic commands ###
